export const BASE_URL = "https://api.themoviedb.org/3"
export const SESSION_TOKEN_URL = "/authentication/token/new"
export const DELETE_SESSION = "/authentication/session"
export const LOGIN_URL = "/authentication/token/validate_with_login"
export const CREATE_SESSION_URL = "/authentication/session/new"
export const API_KEY = "c6a318a694b45925d40ada690e2cba52"
export const ORIGINAL_IMAGE_URL = "https://image.tmdb.org/t/p/original"
export const GRAVATAR_IMAGE_URL = "https://secure.gravatar.com/avatar/"